name: Run Unit Tests on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  setup-python:
    runs-on: windows-latest
    needs: checkout
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

  install-dependencies:
    runs-on: windows-latest
    needs: setup-python
    steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}
          pip install -r requirements.txt

  run-tests:
    runs-on: windows-latest
    needs: install-dependencies
    steps:
      - name: Run Unit Tests
        run: |
          cd ${{ github.workspace }}
          python unittest_RAG.py
